# Web Search Configuration Example
# Copy this file to webSearch.config.yaml and modify as needed

web_search:
  # Default number of search results to return
  default_results: 5
  
  # Search engine settings
  engine: 'google'
  
  # API settings
  api:
    # Your SERP API key
    api_key: 'your-api-key-here'
    
    # Whether to enable real API calls (false for testing)
    enabled: true
    
    # Timeout for API calls in milliseconds
    timeout_ms: 10000
